export class ThemeColor {
  static readonly pageBg: string = '#F2F3F5';
  static readonly card: string = '#FFFFFF';
  static readonly title: string = '#182431';
  static readonly subtitle: string = '#667085';
  static readonly primary: string = '#007DFF';
  static readonly success: string = '#067647';
  static readonly danger: string = '#B42318';
  static readonly divider: string = '#EEF0F3';
  static readonly chipBg: string = '#E8F3FF';
}
